name: date_range_form_field
description: A Flutter package to create a widget which allows the user to input a DateRange into a FormField.
version: 0.0.1
homepage: https://github.com/JMAConsulting/date_range_form_field

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
